#!/usr/bin/env python3
"""
infer_medgemma.py
==================
Runs base MedGemma (google/medgemma-1.5-4b-it) on the reasoning-augmented
parquet dataset WITHOUT any fine-tuning.

Given each row's  image + question  as input, the model generates:
    <reasoning>...</reasoning>
    <answer>...</answer>

The output is saved as a new parquet with columns:
    image      – copied verbatim from source
    question   – copied verbatim from source
    gt_answer  – ground-truth answer copied from source
    gt_reasoning – ground-truth reasoning copied from source
    pred_reasoning – generated by MedGemma
    pred_answer    – generated by MedGemma

This lets you compare base-model output vs the dataset ground truth,
and also serves as a baseline before any fine-tuning.

Usage
-----
    python infer_medgemma.py                         # auto-detects parquet
    python infer_medgemma.py --dataset FILE.parquet  # explicit path
    python infer_medgemma.py --samples 100 --gpu 1   # limit samples, pin GPU

Arguments
---------
--dataset     Path to reasoning_vqa_*.parquet. Auto-detects if omitted.
--model       HuggingFace model ID (default: google/medgemma-1.5-4b-it)
--hf-token    HuggingFace token. Falls back to HF_TOKEN env var.
--samples     Number of rows to run (default: all rows in parquet)
--gpu         GPU index to pin to (auto-selects freest GPU if omitted)
--max-new-tokens  Max tokens to generate per sample (default: 200)
--output-dir  Directory to save output parquet (default: current dir)
--seed        Random seed for sampling (default: 42)
"""

import argparse
import io
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# ── third-party ───────────────────────────────────────────────────────────────
try:
    import torch
    import pandas as pd
    from PIL import Image
    from transformers import AutoProcessor, AutoModelForImageTextToText
    from tqdm import tqdm
except ImportError as e:
    sys.exit(
        f"[ERROR] Missing dependency: {e}\n"
        "  pip install torch transformers Pillow pandas pyarrow tqdm"
    )

# ── constants ─────────────────────────────────────────────────────────────────
DEFAULT_MODEL = "google/medgemma-1.5-4b-it"

# The model is asked to generate BOTH reasoning AND answer from scratch —
# given only the image and the question (no ground-truth hints).
SYSTEM_PROMPT = (
    "You are an expert radiologist and medical imaging assistant. "
    "Given a medical image and a question about it, you must:\n"
    "  1. Look carefully at the image\n"
    "  2. Reason clinically about what you observe (2-3 sentences)\n"
    "  3. Give a concise final answer\n\n"
    "Always respond in this EXACT format — no deviations:\n"
    "<reasoning>\n"
    "[Your 2-3 sentence clinical reasoning based on visual findings]\n"
    "</reasoning>\n"
    "<answer>\n"
    "[Your concise final answer]\n"
    "</answer>"
)


# ── argument parsing ──────────────────────────────────────────────────────────
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Run base MedGemma inference on VQA parquet dataset "
                    "(no fine-tuning). Generates reasoning + answer from image + question."
    )
    p.add_argument("--dataset",        type=str,   default=None,
                   help="Path to .parquet file. Auto-detects reasoning_vqa_*.parquet if omitted.")
    p.add_argument("--model",          type=str,   default=DEFAULT_MODEL,
                   help=f"Model to use (default: {DEFAULT_MODEL})")
    p.add_argument("--hf-token",       type=str,   default=None,
                   help="HuggingFace token for gated model access")
    p.add_argument("--samples",        type=int,   default=None,
                   help="Number of rows to process. Default: all rows in the parquet.")
    p.add_argument("--gpu",            type=int,   default=None,
                   help="GPU index to pin to. Auto-selects freest GPU if omitted.")
    p.add_argument("--max-new-tokens", type=int,   default=200,
                   help="Maximum tokens to generate per sample (default: 200)")
    p.add_argument("--output-dir",     type=str,   default=".",
                   help="Directory to save output parquet (default: current dir)")
    p.add_argument("--seed",           type=int,   default=42,
                   help="Random seed for row sampling (default: 42)")
    return p.parse_args()


# ── helpers ───────────────────────────────────────────────────────────────────
def resolve_token(cli: Optional[str]) -> Optional[str]:
    return cli or os.environ.get("HF_TOKEN", None)


def pin_gpu(requested: Optional[int]) -> str:
    """
    Pin to a single GPU by setting CUDA_VISIBLE_DEVICES.
    Prevents DataParallel from spreading across multiple partially-occupied GPUs.
    """
    if not torch.cuda.is_available():
        return "cpu"
    n = torch.cuda.device_count()
    if n == 0:
        return "cpu"

    if requested is not None:
        idx = requested % n
    else:
        # Auto-select GPU with the most free VRAM
        free = []
        for i in range(n):
            try:
                f, _ = torch.cuda.mem_get_info(i)
                free.append((f, i))
            except Exception:
                free.append((0, i))
        idx = max(free)[1]

    os.environ["CUDA_VISIBLE_DEVICES"] = str(idx)
    torch.cuda.empty_cache()
    free_gb  = torch.cuda.mem_get_info(0)[0] / 1024 ** 3
    total_gb = torch.cuda.mem_get_info(0)[1] / 1024 ** 3
    print(f"  GPU {idx}: {torch.cuda.get_device_name(0)}  "
          f"({free_gb:.1f} / {total_gb:.1f} GiB free)")
    return "cuda"


def autodetect_parquet() -> str:
    """Find the most recently modified reasoning_vqa_*.parquet in cwd."""
    cwd = Path(".")
    for pattern in ("reasoning_vqa_*.parquet", "*.parquet"):
        hits = sorted(cwd.glob(pattern),
                      key=lambda p: p.stat().st_mtime, reverse=True)
        if hits:
            return str(hits[0])
    sys.exit(
        "[ERROR] No parquet file found in current directory.\n"
        "  Run create_reasoning_vqa_dataset.py first, or pass --dataset PATH"
    )


def bytes_to_pil(b: Any) -> Image.Image:
    """Convert parquet image bytes back to a PIL RGB image."""
    if isinstance(b, Image.Image):
        return b.convert("RGB")
    if isinstance(b, (bytes, bytearray, memoryview)):
        return Image.open(io.BytesIO(bytes(b))).convert("RGB")
    if hasattr(b, "tobytes"):
        return Image.open(io.BytesIO(b.tobytes())).convert("RGB")
    raise ValueError(f"Cannot convert type {type(b)} to PIL Image")


def pil_to_bytes(img: Image.Image) -> bytes:
    """Encode PIL image back to PNG bytes for parquet storage."""
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def parse_model_output(text: str) -> Tuple[str, str]:
    """
    Extract <reasoning> and <answer> blocks from raw model output.

    If the model didn't follow the format exactly, falls back gracefully:
    - Everything before the last sentence → reasoning
    - Last sentence → answer
    """
    r_match = re.search(
        r"<reasoning>\s*(.*?)\s*</reasoning>", text, re.DOTALL | re.IGNORECASE
    )
    a_match = re.search(
        r"<answer>\s*(.*?)\s*</answer>", text, re.DOTALL | re.IGNORECASE
    )

    reasoning = r_match.group(1).strip() if r_match else ""
    answer    = a_match.group(1).strip() if a_match else ""

    # Fallback: if tags are missing, split raw text heuristically
    if not reasoning and not answer:
        sentences = [s.strip() for s in re.split(r"(?<=[.!?])\s+", text.strip()) if s.strip()]
        if len(sentences) > 1:
            reasoning = " ".join(sentences[:-1])
            answer    = sentences[-1]
        else:
            reasoning = ""
            answer    = text.strip()

    return reasoning, answer


# ── model inference ───────────────────────────────────────────────────────────
def run_inference(
    processor,
    model,
    image: Image.Image,
    question: str,
    device: str,
    max_new_tokens: int,
) -> Tuple[str, str]:
    """
    Run a single forward pass with image + question as input.
    Returns (reasoning, answer) — both generated by the model.

    Input to model:
        system prompt + image + question

    Model generates:
        <reasoning>...</reasoning>
        <answer>...</answer>
    """
    messages = [
        {
            "role": "system",
            "content": [{"type": "text", "text": SYSTEM_PROMPT}],
        },
        {
            "role": "user",
            "content": [
                {"type": "image", "image": image},
                {"type": "text",  "text": question},
            ],
        },
    ]

    # Tokenize using the chat template
    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,   # adds the assistant turn start token
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
    ).to("cuda" if device == "cuda" else "cpu")

    input_len = inputs["input_ids"].shape[-1]

    # Generate new tokens only — greedy decoding for deterministic output
    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,          # greedy — reproducible results
        )

    # Slice off only the newly generated tokens (strip the input prompt)
    new_tokens = output_ids[0][input_len:]
    raw_output = processor.decode(new_tokens, skip_special_tokens=True).strip()

    # Parse <reasoning> and <answer> tags from raw output
    reasoning, answer = parse_model_output(raw_output)
    return reasoning, answer


# ── main ──────────────────────────────────────────────────────────────────────
def main() -> None:
    args     = parse_args()
    hf_token = resolve_token(args.hf_token)

    # 0. Pin GPU before any CUDA allocation
    print("\n[0/4] Selecting GPU...")
    device = pin_gpu(args.gpu)

    print(f"\n{'='*62}")
    print(f"  Model          : {args.model}")
    print(f"  Device         : {device}")
    print(f"  Max new tokens : {args.max_new_tokens}")
    print(f"  Output dir     : {args.output_dir}")
    print(f"\n  INPUT  → image + question")
    print(f"  OUTPUT → reasoning + answer  (generated by model)")
    print(f"{'='*62}\n")

    # 1. Load parquet
    print("[1/4] Loading dataset...")
    if args.dataset is None:
        args.dataset = autodetect_parquet()
        print(f"  Auto-detected: {args.dataset}")
    elif not Path(args.dataset).exists():
        sys.exit(f"[ERROR] File not found: {args.dataset!r}")

    df = pd.read_parquet(args.dataset)

    # Validate required columns
    required = {"image", "question", "answer", "reasoning"}
    missing  = required - set(df.columns)
    if missing:
        sys.exit(
            f"[ERROR] Parquet missing columns: {missing}\n"
            f"  Found: {list(df.columns)}"
        )

    # Optionally sample a subset of rows
    if args.samples is not None:
        df = df.sample(
            min(args.samples, len(df)),
            random_state=args.seed
        ).reset_index(drop=True)

    print(f"  File    : {args.dataset}")
    print(f"  Columns : {list(df.columns)}")
    print(f"  Rows    : {len(df)}")

    # 2. Load model
    print("\n[2/4] Loading MedGemma model...")
    load_kw: Dict[str, Any] = {"dtype": torch.bfloat16}
    if hf_token:
        load_kw["token"] = hf_token

    try:
        processor = AutoProcessor.from_pretrained(args.model, **load_kw)
        model = AutoModelForImageTextToText.from_pretrained(
            args.model,
            device_map={"": 0} if device == "cuda" else None,
            **load_kw,
        )
        model.eval()
        print(f"  Loaded: {args.model}  (bfloat16)")
    except Exception as e:
        sys.exit(
            f"[ERROR] Could not load model '{args.model}'.\n  {e}\n\n"
            "  1. Accept model terms: huggingface.co/google/medgemma-1.5-4b-it\n"
            "  2. export HF_TOKEN=hf_...  or pass --hf-token\n"
            "  3. Free up GPU memory — need ~8 GB for bfloat16"
        )

    # 3. Run inference on every row
    print(f"\n[3/4] Running inference on {len(df)} rows...")
    results: List[Dict[str, Any]] = []
    errors  = 0

    for _, row in tqdm(df.iterrows(), total=len(df), desc="Inferring"):
        try:
            image = bytes_to_pil(row["image"])
        except Exception as e:
            tqdm.write(f"  ⚠  Could not decode image: {e} — skipping")
            errors += 1
            continue

        try:
            pred_reasoning, pred_answer = run_inference(
                processor, model,
                image, str(row["question"]),
                device, args.max_new_tokens,
            )
        except Exception as e:
            tqdm.write(f"  ⚠  Inference error: {e} — skipping")
            errors += 1
            continue

        results.append({
            # ── input columns (verbatim from source) ──────────────────────────
            "image"         : pil_to_bytes(image),    # PNG bytes
            "question"      : str(row["question"]),
            # ── ground truth (from dataset) ───────────────────────────────────
            "gt_answer"     : str(row["answer"]),
            "gt_reasoning"  : str(row["reasoning"]),
            # ── model predictions (generated from image + question only) ──────
            "pred_reasoning": pred_reasoning,
            "pred_answer"   : pred_answer,
        })

    print(f"\n  → {len(results)} rows generated  ({errors} errors skipped)")

    if not results:
        sys.exit("[ERROR] No results generated. Cannot write output file.")

    # 4. Save output parquet
    print("\n[4/4] Saving output...")
    timestamp    = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_filename = f"infer_results_{len(results)}rows_{timestamp}.parquet"
    out_path     = Path(args.output_dir) / out_filename
    out_path.parent.mkdir(parents=True, exist_ok=True)

    out_df = pd.DataFrame(results)
    out_df.to_parquet(out_path, index=False, engine="pyarrow")

    size_mb = out_path.stat().st_size / (1024 * 1024)

    print(f"\n{'='*62}")
    print(f"✅  Inference complete")
    print(f"   Rows processed : {len(results)}")
    print(f"   Errors skipped : {errors}")
    print(f"   Output file    : {out_path}")
    print(f"   File size      : {size_mb:.1f} MB")
    print(f"\n   Output columns:")
    print(f"     image          – PNG bytes (same image as input)")
    print(f"     question       – original question (verbatim)")
    print(f"     gt_answer      – ground-truth answer from dataset")
    print(f"     gt_reasoning   – ground-truth reasoning from dataset")
    print(f"     pred_reasoning – generated by {args.model}")
    print(f"     pred_answer    – generated by {args.model}")
    print(f"{'='*62}")

    # Quick preview of first result
    if results:
        r = results[0]
        print(f"\nFirst row preview:")
        print(f"  Question       : {r['question'][:120]}")
        print(f"  GT answer      : {r['gt_answer'][:120]}")
        print(f"  Pred answer    : {r['pred_answer'][:120]}")
        print(f"  GT reasoning   : {r['gt_reasoning'][:200]}...")
        print(f"  Pred reasoning : {r['pred_reasoning'][:200]}...")


if __name__ == "__main__":
    main()
